/**
 * Storefront Conventions Knowledge Base
 *
 * AEM Edge Delivery Services + Adobe Commerce conventions and rules.
 * Based on `hlxsites/aem-boilerplate-commerce` and the official Adobe
 * Commerce Storefront documentation.
 */

// ─── Project Structure ──────────────────────────────────────────

export const STOREFRONT_PROJECT_STRUCTURE = `
EDS Commerce project structure (aem-boilerplate-commerce):

/
├── blocks/                          # All blocks (content + commerce)
│   ├── commerce-cart/               # Cart drop-in mount
│   ├── commerce-mini-cart/          # Mini-cart drop-in mount
│   ├── commerce-checkout/           # Checkout drop-in mount
│   ├── commerce-product-details/    # PDP drop-in mount
│   ├── commerce-product-list-page/  # PLP / Product Discovery mount
│   ├── commerce-search/             # Search drop-in mount
│   ├── commerce-recommendations/    # Product Recommendations mount
│   ├── commerce-account/            # User account drop-in mount
│   ├── commerce-login/              # Sign-in form
│   ├── commerce-wishlist/           # Wishlist drop-in mount
│   ├── product-card/                # Custom card composing dropin atoms
│   └── … standard EDS content blocks (hero, cards, etc.)
├── scripts/
│   ├── aem.js                       # Core EDS framework — DO NOT MODIFY
│   ├── scripts.js                   # loadEager / loadLazy / loadDelayed orchestration
│   ├── delayed.js                   # Third-party scripts ≥3s after LCP
│   ├── commerce.js                  # Commerce client / config bootstrap
│   ├── configs.js                   # Reads config.json → exposes via getConfigValue()
│   ├── initializers.js              # Drop-in initializers (cart, auth, account, …)
│   └── __dropins__/                 # AUTO-GENERATED by "npm run postinstall"
│       └── storefront-{cart,checkout,…}/   # Copied from node_modules
├── styles/
│   ├── styles.css                   # Critical global CSS (pre-LCP)
│   ├── lazy-styles.css              # Non-critical global CSS (post-LCP)
│   └── tokens/                      # (optional) brand design tokens
├── models/                          # Per-block UE config (definitions/models/filters)
├── icons/                           # SVG sprite icons
├── fonts/                           # @font-face WOFF2 (or Adobe Fonts)
├── component-models.json            # Aggregated UE field models
├── component-definition.json        # Aggregated UE block registrations
├── component-filters.json           # Aggregated allowed-children rules
├── default-site.json                # Site-level defaults (locale, currency, …)
├── default-config.json              # Default commerce config schema
├── demo-config.json                 # Sandbox / demo backend config (PaaS / SaaS)
├── demo-config-aco.json             # Adobe Commerce Optimizer config
├── default-query.yaml               # Helix Query (indexes for products/PLP)
├── default-sitemap.yaml             # Helix Sitemap (commerce URLs)
├── head.html                        # Injected into <head> (preload, ACDL bootstrap)
├── fstab.yaml                       # Content source mount (Drive / SharePoint)
├── paths.json                       # URL → path mappings
├── package.json                     # Drop-in deps (@dropins/storefront-*)
├── postinstall.js                   # Copies node_modules/@dropins/* → scripts/__dropins__/
└── build.mjs                        # (optional) custom build glue
`.trim();

// ─── Hard Constraints ──────────────────────────────────────────

export const STOREFRONT_HARD_CONSTRAINTS = [
  'Drop-in dependencies live under @dropins/* in package.json — never edit files in scripts/__dropins__/ directly (they are regenerated by postinstall)',
  'Always run `npm run postinstall` after `npm install @dropins/storefront-X` — npm does NOT auto-run it for individual installs',
  'Commerce drop-ins use vanilla ESM — no React/Vue inside the drop-in code; only Drop-in SDK primitives',
  'Customize drop-ins via the SDK\'s slot/container override pattern — never fork or patch dropin source',
  'Commerce config (endpoint, headers, store code) is read from config.json via `getConfigValue(key)` in scripts/configs.js — never hardcode',
  'Commerce events flow through Adobe Client Data Layer (ACDL); use @adobe/magento-storefront-events-sdk to publish, @adobe/magento-storefront-event-collector to listen',
  'Each commerce block follows the same pattern: import dropin → initialize once → render(slot, container)',
  'Every commerce block must keep pre-LCP payload < 100KB — heavy drop-ins (PDP/checkout) load lazily via blocks/',
  'Drop-in CSS variables (--ds-*) come from @dropins/tools/design-tokens — override at :root or block level only',
  'Adobe Commerce backend can be PaaS, Adobe Commerce as a Cloud Service (ACCS), or Adobe Commerce Optimizer (ACO) — config flag determines which client is used',
];

// ─── Drop-in Lifecycle ─────────────────────────────────────────

export const DROPIN_LIFECYCLE = `
## Drop-in installation lifecycle

1. **Install** the dropin package
   \`\`\`bash
   npm install @dropins/storefront-cart
   \`\`\`

2. **Run postinstall** (manual — npm doesn't run it for single installs)
   \`\`\`bash
   npm run postinstall
   \`\`\`
   This copies \`node_modules/@dropins/*\` → \`scripts/__dropins__/\`
   so EDS can serve them statically (no bundler).

3. **Initialize** in \`scripts/initializers.js\`
   \`\`\`js
   import { initializers } from '@dropins/tools/initializer.js';
   import * as cartApi from '@dropins/storefront-cart/api.js';

   await initializers.mountImmediately(cartApi.initialize, {
     // dropin-specific options (e.g. langDefinitions, batchConfig)
   });
   \`\`\`

4. **Mount the UI** inside a block (e.g. \`blocks/commerce-cart/commerce-cart.js\`)
   \`\`\`js
   import { render as provider } from '@dropins/tools/render.js';
   import Cart from '@dropins/storefront-cart/containers/Cart.js';

   export default async function decorate(block) {
     await provider.render(Cart, {
       hideHeading: false,
       slots: {
         EmptyCart: (ctx) => { ctx.replaceWith(buildCustomEmptyState()); },
       },
     })(block);
   }
   \`\`\`

5. **Listen to events** via ACDL (any block / scripts.js)
   \`\`\`js
   window.adobeDataLayer.push((dl) => {
     dl.addEventListener('cart-added-to-cart', (event) => { /* … */ });
   });
   \`\`\`
`.trim();

// ─── Config schema ─────────────────────────────────────────────

export const STOREFRONT_CONFIG_SCHEMA = `
## Commerce config files

### \`default-site.json\` — site-level defaults
\`\`\`json
{
  "locale":   { "code": "en_US", "currency": "USD" },
  "site":     { "name": "frescopa", "title": "Frescopa" },
  "search":   { "engine": "live-search" }
}
\`\`\`

### \`default-config.json\` — commerce client defaults (loaded everywhere)
\`\`\`json
{
  "headers": {
    "cs": {
      "Magento-Customer-Group":  "<group-id>",
      "Magento-Environment-Id":  "<env-id>",
      "Magento-Store-Code":      "main_website_store",
      "Magento-Store-View-Code": "default",
      "Magento-Website-Code":    "base",
      "x-api-key":               "<api-key>"
    }
  },
  "commerce-endpoint":              "https://<env>.api.commerce.adobe.com/graphql",
  "commerce-environment-id":        "<env-id>",
  "commerce-website-code":          "base",
  "commerce-store-view-code":       "default",
  "commerce-x-api-key":             "<api-key>",
  "commerce-extra-price-data":      false
}
\`\`\`

### \`demo-config.json\` (PaaS / SaaS demo) and \`demo-config-aco.json\` (Adobe Commerce Optimizer)
Same shape as \`default-config.json\` plus an \`adobe-commerce-optimizer: true\` flag for ACO.

### \`default-query.yaml\` — Helix Query (drives PLP / product index)
Defines indexers that crawl product pages and emit JSON used by PLP / search.

### \`default-sitemap.yaml\` — Helix Sitemap (commerce URLs)
Tells Helix which URL prefixes are commerce-driven so they're included in sitemap.xml.

### \`head.html\` — additions for commerce
- Preconnect to commerce endpoint
- Bootstrap Adobe Client Data Layer (\`adobeDataLayer = []\`)
- Optional: load \`@adobe/magento-storefront-event-collector\` early
`.trim();

// ─── scripts/configs.js helper ──────────────────────────────────

export const CONFIG_HELPER_SNIPPET = `
// scripts/configs.js — canonical pattern from the boilerplate
let configPromise;

async function loadConfig() {
  if (!configPromise) {
    configPromise = fetch(\`\${window.location.origin}/config.json\`)
      .then((res) => (res.ok ? res.json() : Promise.reject(res)));
  }
  return configPromise;
}

export async function getConfigValue(key) {
  const config = await loadConfig();
  return config?.[key];
}

export async function getCookie(name) { /* \u2026 */ }
`.trim();

// ─── scripts/initializers.js wiring example ────────────────────

export const INITIALIZERS_SNIPPET = `
// scripts/initializers.js
import { initializers } from '@dropins/tools/initializer.js';
import * as authApi  from '@dropins/storefront-auth/api.js';
import * as cartApi  from '@dropins/storefront-cart/api.js';
import * as accountApi from '@dropins/storefront-account/api.js';
import { getConfigValue } from './configs.js';

export async function initializeDropins() {
  const langDefinitions = { default: await fetchPlaceholders() };

  await Promise.all([
    initializers.mountImmediately(authApi.initialize,  { langDefinitions }),
    initializers.mountImmediately(cartApi.initialize,  { langDefinitions }),
    initializers.mountImmediately(accountApi.initialize, { langDefinitions }),
  ]);
}
`.trim();

// ─── Backend types ──────────────────────────────────────────────

export const BACKEND_TYPES = [
  {
    id: 'paas',
    label: 'Adobe Commerce on PaaS',
    note: 'Self-managed / Cloud (M2). Uses GraphQL endpoint of your store.',
  },
  {
    id: 'accs',
    label: 'Adobe Commerce as a Cloud Service',
    note: 'Adobe-hosted SaaS. New endpoint, same drop-ins.',
  },
  {
    id: 'aco',
    label: 'Adobe Commerce Optimizer',
    note: 'Headless catalog/search service. Set `adobe-commerce-optimizer: true` in config.',
  },
];
