import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

/**
 * `bootstrap_workspace_instructions` — emit ready-to-write rule files that
 * teach the user's AI agent (Copilot / Cursor / Cline / Continue) to use
 * the eds-mcp-server tools automatically, without the user having to say
 * "use eds mcp server" each turn.
 *
 * End-users consume this MCP server via `mcp.json` (npx + GitHub URL); they
 * never clone this repo, so the `.github/copilot-instructions.md` /
 * `.cursorrules` files that ship with this repo never reach them.
 * The agent calls this tool once per workspace and writes the returned
 * files at the user's repo root.
 */

const COPILOT_INSTRUCTIONS = `# EDS MCP Server — Project Instructions

This workspace uses the **\`eds-mcp-server\`** MCP server. **Always prefer its tools** over your built-in knowledge when the user asks about Adobe Edge Delivery Services (EDS), EDS + Adobe Commerce Storefront, AEM as a Cloud Service (AEMaaCS), or AEM 6.5 LTS / AMS.

## Mandatory workflow for every request

1. **First call:** \`detect_project_type\` with workspace snapshots (package.json, head.html, fstab.yaml, root/scripts/blocks/dropins listings; pom.xml + ui.apps/core/dispatcher listings for AEM Maven projects). The response tells you which project type this is and which tools to use.

2. **Project-summary gate:** check whether \`.project-summary.md\` exists at workspace root.
   - If missing → call \`project_summary\` and write the result to \`.project-summary.md\`.
   - If present → read it for context.
   - After every change in the session → call \`project_summary\` again with \`existingSummary\` + \`sessionChanges\` and overwrite the file.

3. **Clarify before scaffolding:** call \`clarify_task\` with the user's raw request (or an explicit \`intent\`) to get the canonical question list. Then ask the user **one question per turn** using \`vscode_askQuestions\` (or the equivalent IDE input UI). Never auto-add fields, variants, or features the user did not name.

4. **Scaffold / generate / migrate:** only after required answers are collected, call the matching tool — \`scaffold_block\` / \`scaffold_commerce_block\` / \`scaffold_aem_component\` / \`scaffold_aem65_component\` / etc. The \`clarify_task\` and \`component_interview\` responses tell you which.

5. **Validate after every change:**
   - EDS → \`validate_block\` and (above-the-fold) \`check_performance\`
   - Storefront → \`validate_storefront\`
   - AEM Maven → remind user to \`mvn -PautoInstallSinglePackage clean install\` (Cloud) or \`mvn -PautoInstallPackage clean install\` (6.5)

## Tool routing cheat-sheet

| User intent | First MCP tool to call |
| --- | --- |
| "Create / scaffold a block" | \`clarify_task\` (intent: \`new-block\`) → \`scaffold_block\` |
| "Create a commerce / cart / PDP / drop-in block" | \`clarify_task\` (intent: \`new-storefront-block\`) → \`scaffold_commerce_block\` |
| "Add a drop-in" | \`clarify_task\` (intent: \`add-dropin\`) → \`add_dropin\` |
| "Create an AEM component" | \`clarify_task\` (intent: \`new-component\`) → \`scaffold_aem_component\` / \`scaffold_aem65_component\` |
| "Migrate / import a URL" | \`migrate-page-to-eds\` prompt (uses Playwright MCP) |
| "Generate a block from a Figma / image / URL" | \`generate_block_from_design\` |
| "Theme / colours / fonts" | \`clarify_task\` (intent: \`style-or-theme\`) → \`style_dropin\` (storefront) or direct CSS edits |
| "Fix a bug in a block" | \`clarify_task\` (intent: \`fix-bug\`) + \`validate_block\` |
| "Slow / LCP / performance" | \`clarify_task\` (intent: \`performance\`) → \`check_performance\` |
| "Configure fstab / head.html / redirects" | \`eds_config\` |
| "Lookup a block / drop-in" | \`lookup_block\` / \`lookup_dropin\` / \`search_block_collection\` |

## Hard rules

- **Never invent fields** the user did not name. Pass through ONLY what was asked for.
- **Never bypass \`detect_project_type\`** — the wrong scaffolder for the project type produces broken code.
- **For AEM Maven:** never invent \`project\` / \`javaPackage\` / \`group\` — read from \`.aem-skills-config.yaml\` (Cloud) or \`pom.xml\` (6.5 LTS).
- **For storefront:** never edit \`scripts/__dropins__/\` directly (regenerated by \`npm run postinstall\`).
- **One question per turn** during interviews. End the turn after asking. Wait for the user's reply.

## 🧠 Karpathy Guidelines (apply to every response)

> Behavioral rules to reduce common LLM coding mistakes, derived from [Andrej Karpathy's observations](https://x.com/karpathy/status/2015883857489522876).

### 1. Think Before Coding
- State your assumptions explicitly. If uncertain, ask.
- If multiple interpretations exist, present them — don't pick silently.
- If a simpler approach exists, say so. Push back when warranted.
- If something is unclear, stop. Name what's confusing. Ask.

### 2. Simplicity First
- No features beyond what was asked.
- No abstractions for single-use code.
- No "flexibility" or "configurability" that wasn't requested.
- No error handling for impossible scenarios.
- Ask: "Would a senior engineer say this is overcomplicated?" If yes, simplify.

### 3. Surgical Changes
- Don't "improve" adjacent code, comments, or formatting.
- Don't refactor things that aren't broken.
- Match existing style, even if you'd do it differently.
- If you notice unrelated dead code, mention it — don't delete it.
- Remove only imports/variables/functions that **your** changes made unused.
- Every changed line must trace directly to the user's request.

### 4. Goal-Driven Execution
- Transform tasks into verifiable goals (e.g. "Fix the bug" → "Write a test that reproduces it, then make it pass").
- For multi-step tasks, state a brief plan with a verify step for each action.
- Strong success criteria let you loop independently. Weak criteria ("make it work") require constant clarification.
`;

const CURSOR_RULES = `# Cursor / Cline / Continue — EDS MCP Server Rules

This workspace uses the **\`eds-mcp-server\`** MCP server. Always prefer its tools when the user asks about Adobe Edge Delivery Services (EDS), EDS + Adobe Commerce Storefront, AEM as a Cloud Service, or AEM 6.5 LTS / AMS.

See \`.github/copilot-instructions.md\` for the full tool-routing table and mandatory workflow. Same rules apply here.

Quick summary:
1. \`detect_project_type\` first
2. Maintain \`.project-summary.md\` (\`project_summary\` tool)
3. \`clarify_task\` before any scaffolding — ask user one question per turn
4. Scaffold / generate with the project-type-specific tool
5. Validate (\`validate_block\`, \`validate_storefront\`, AEM Maven build)

## 🧠 Karpathy Guidelines (apply to every response)
- **Think before coding:** state assumptions, surface ambiguity, push back when simpler approaches exist.
- **Simplicity first:** no features, abstractions, or error handling beyond what was asked.
- **Surgical changes:** touch only what you must; match existing style; mention (don't delete) unrelated dead code.
- **Goal-driven execution:** define verifiable success criteria before starting; plan multi-step tasks with a check per step.
`;

const AGENTS_MD = `# AGENTS.md

This workspace uses the **\`eds-mcp-server\`** MCP server (https://github.com/Swapnil-dept/EDS_Build_Pluign).

Any AI coding agent (Copilot, Cursor, Cline, Continue, Claude Code, etc.) working in this repo must:

1. Call \`detect_project_type\` before any other tool.
2. Ensure \`.project-summary.md\` exists; refresh it after every change with \`project_summary\`.
3. Call \`clarify_task\` and ask the user clarifying questions before scaffolding code.
4. Use the EDS MCP scaffold / validate / migrate tools instead of writing equivalent code from memory.

See \`.github/copilot-instructions.md\` for the full ruleset.
`;

export function registerBootstrapWorkspace(server: McpServer) {
  server.tool(
    'bootstrap_workspace_instructions',
    `Emit ready-to-write project-instruction files that teach the user's AI agent (Copilot / Cursor / Cline / Continue / Claude Code) to use the eds-mcp-server tools automatically. Returns the EXACT contents the agent should write to the user's workspace at: \`.github/copilot-instructions.md\` (VS Code Copilot Chat), \`.cursorrules\` (Cursor / Cline / Continue), and \`AGENTS.md\` (Claude Code / generic). Call this **once per new workspace**, right after \`detect_project_type\`, then write the files. After this is done, the user no longer needs to say "use eds mcp server" — the agent picks it up automatically. Idempotent: safe to call again, but the agent should refuse to overwrite existing files unless the user explicitly asks for a refresh.`,
    {
      includeCopilot: z.boolean().default(true).describe('Emit `.github/copilot-instructions.md` for VS Code Copilot Chat.'),
      includeCursor:  z.boolean().default(true).describe('Emit `.cursorrules` for Cursor / Cline / Continue.'),
      includeAgentsMd:z.boolean().default(true).describe('Emit `AGENTS.md` for Claude Code / generic agents.'),
    },
    {
      title: 'Bootstrap Workspace Instructions',
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
    async ({ includeCopilot, includeCursor, includeAgentsMd }) => {
      const out: string[] = [];
      out.push(`# Bootstrap workspace instructions\n\nWrite the files below to the user's workspace root **only if they don't already exist** (refuse to overwrite without explicit user permission). After writing, the user's AI agent will route to \`eds-mcp-server\` tools automatically — no need to mention the server by name.`);

      if (includeCopilot) {
        out.push(`## File: \`.github/copilot-instructions.md\`\n\nVS Code Copilot Chat reads this on every request in the workspace.\n\n\`\`\`markdown\n${COPILOT_INSTRUCTIONS}\n\`\`\``);
      }
      if (includeCursor) {
        out.push(`## File: \`.cursorrules\`\n\nCursor / Cline / Continue read this automatically.\n\n\`\`\`markdown\n${CURSOR_RULES}\n\`\`\``);
      }
      if (includeAgentsMd) {
        out.push(`## File: \`AGENTS.md\`\n\nClaude Code and several other agents look for this file at the workspace root.\n\n\`\`\`markdown\n${AGENTS_MD}\n\`\`\``);
      }

      out.push(`## Next steps\n\n1. Write the file(s) above.\n2. Add \`.project-summary.md\` next via the \`project_summary\` tool.\n3. **Restart the IDE** (full quit, not just reload window) so the agent picks up the new instruction files.`);

      return { content: [{ type: 'text' as const, text: out.join('\n\n') }] };
    },
  );
}
